### ISSUE TITLE
LoRAS  : can you share updated code pls

### ISSUE THREAD

**Issue by Sandy4321** [zoj613/polya-gamma#27]
This version does not yet include the t-embedding parameter.
can you share updated code pls

https://link.springer.com/article/10.1007%2Fs10994-020-05913-4

Code availability A preliminary implementation of the algorithm in Python (V 3.7.4) and an example
Jupyter Notebook for the credit card fraud detection dataset is provided on the GitHub repository
https ://githu b.com/sbi-rosto ck/LoRAS . This version does not yet include the t-embedding parameter.

**Comment by zoj613** [comment]
I think you meant to post this in another repo.
